name: Publish Docker Images

on:
  schedule:
    - cron: "30 5 * * SUN"
  workflow_run:
    workflows:
      - "Update Building System"
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:

  cancel_previous_runs:
    runs-on: ubuntu-latest
    steps:
    -
      name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

  push_to_registry-R_4_3_0:
    needs: cancel_previous_runs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        rversion: ['4.3.0']
        image: ['r-aws-minimal', 'r-aws-spatial', 'r-cicd-minimal', 'r-cicd-spatial']
    name: ${{ matrix.image }} - ${{ matrix.rversion }}
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    -
      name: Create Tags for Docker image
      uses: haya14busa/action-cond@v1
      id: condtag
      with:
        cond: ${{ matrix.rversion == '4.3.2' }}
        if_true: "meterds/${{ matrix.image }}:latest, meterds/${{ matrix.image }}:${{ matrix.rversion }}"
        if_false: "meterds/${{ matrix.image }}:${{ matrix.rversion }}"
    -
      name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        file: dockerfiles/${{ matrix.image }}_${{ matrix.rversion }}.Dockerfile
        push: true
        tags: ${{ steps.condtag.outputs.value }}

  push_to_registry-R_4_3_1:
    needs: cancel_previous_runs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        rversion: ['4.3.1']
        image: ['r-aws-minimal', 'r-aws-spatial', 'r-cicd-minimal', 'r-cicd-spatial']
    name: ${{ matrix.image }} - ${{ matrix.rversion }}
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    -
      name: Create Tags for Docker image
      uses: haya14busa/action-cond@v1
      id: condtag
      with:
        cond: ${{ matrix.rversion == '4.3.2' }}
        if_true: "meterds/${{ matrix.image }}:latest, meterds/${{ matrix.image }}:${{ matrix.rversion }}"
        if_false: "meterds/${{ matrix.image }}:${{ matrix.rversion }}"
    -
      name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        file: dockerfiles/${{ matrix.image }}_${{ matrix.rversion }}.Dockerfile
        push: true
        tags: ${{ steps.condtag.outputs.value }}

  push_to_registry-R_4_3_2:
    needs: cancel_previous_runs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        rversion: ['4.3.2']
        image: ['r-aws-minimal', 'r-aws-spatial', 'r-cicd-minimal', 'r-cicd-spatial']
    name: ${{ matrix.image }} - ${{ matrix.rversion }}
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    -
      name: Create Tags for Docker image
      uses: haya14busa/action-cond@v1
      id: condtag
      with:
        cond: ${{ matrix.rversion == '4.3.2' }}
        if_true: "meterds/${{ matrix.image }}:latest, meterds/${{ matrix.image }}:${{ matrix.rversion }}"
        if_false: "meterds/${{ matrix.image }}:${{ matrix.rversion }}"
    -
      name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        file: dockerfiles/${{ matrix.image }}_${{ matrix.rversion }}.Dockerfile
        push: true
        tags: ${{ steps.condtag.outputs.value }}

